---
- name: Install UltraVNC on all Windows hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Create destination directory on Windows
      win_file:
        path: C:\Temp\Downloads
        state: directory

    - name: Copy UltraVNC installer to Windows machine
      ansible.builtin.copy:
        src: /home/filipgrk/downloads/UltraVNC_1436_X64_Setup.exe
        dest: C:\Temp\Downloads\UltraVNC_1436_X64_Setup.exe
        mode: '0755'

    - name: Install UltraVNC silently
      win_package:
        path: C:\Temp\Downloads\UltraVNC_1436_X64_Setup.exe
        product_id: "{PRODUCT_ID_OF_ULTRAVNC}"
        arguments: '/SILENT /NORESTART'

    - name: Ensure UltraVNC service is running
      win_service:
        name: "uvnc_service"
        start_mode: auto
        state: started

    - name: Clean up UltraVNC installer
      win_file:
        path: C:\Temp\Downloads\UltraVNC_1436_X64_Setup.exe
        state: absent