---
- name: Install UltraVNC on all Windows hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Download UltraVNC installer
      win_get_url:
        url: "https://uvnc.eu/download/1436/UltraVNC_1436_X64_Setup.exe;"
        dest: C:\Temp\UltraVNC_1436_X64_Setup.exe
      register: download_status

    - name: Install UltraVNC server
      win_package:
        path: C:\Temp\UltraVNC_1436_X64_Setup.exe
        product_id: "{PRODUCT_ID_OF_ULTRAVNC}"
        arguments: '/SILENT /NORESTART'
      when: download_status is succeeded

    - name: Ensure UltraVNC service is running
      win_service:
        name: "uvnc_service"
        start_mode: auto
        state: started

    - name: Clean up UltraVNC installer
      win_file:
        path: C:\Temp\UltraVNC_1436_X64_Setup.exe
        state: absent