---
- name: Apply all available Windows updates
  hosts: all
  gather_facts: no
  tasks:
    - name: Install all available Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
      register: update_result
      until: update_result.updates | length == 0
      retries: 5
      delay: 300  # Wait for 5 minutes between retries

    - name: Reboot the machine if updates were applied
      win_reboot:
      when: update_result.reboot_required
      retries: 5
      delay: 300  # Delay to allow reboot to complete before retrying

    - name: Check if more updates are available after reboot
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
      register: post_reboot_updates
      until: post_reboot_updates.updates | length == 0
      retries: 5
      delay: 300  # Retry every 5 minutes to ensure no more updates are available

    - name: Reboot again if more updates were installed after the first reboot
      win_reboot:
      when: post_reboot_updates.reboot_required
      retries: 5
      delay: 300  # Delay to allow reboot