---
- name: Apply the latest Windows updates
  hosts: all
  gather_facts: no
  tasks:
    - name: Install all available Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
      register: update_result

    - name: Reboot the machine if updates were applied
      win_reboot:
      when: update_result.reboot_required
